services:
  web:
    build: .
    command: python -u manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/articles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
