# Generated by Django 4.2.11 on 2024-05-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='article_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
